services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
  node_app:
    image: gym_node_app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env